### PR TITLE
Updated dependency

### PR DESCRIPTION
**Pull request by senzidee**
Hi Carl,
I have updated dependency. With the new version of rocket, now, it's possible to use stable version of rust.
By the way, this tool is amazing for simple logs view.

### CODE REVIEW

**Comment by cfsamson** [comment]
Hi and thanks for the PR. I have this installed on a few computers but haven't gotten around to update it in a long time so this is great. Glad to hear you've found it useful as well!

**Comment by cfsamson** [comment]
Just to double check but if I'm not mistaken there is no need for nightly anymore when using Rocket, right? If so I'll update the readme as well to reflect that.

**Comment by senzidee** [comment]
Yes, no more.

**Comment by cfsamson** [comment]
Perfect. I've published a new version to crates.io 👍

**Comment by senzidee** [comment]
Wonderful!! Thank you for accepting my PR

**Pull request merged**
